#126 Add share functionality
sfbrigade/datasci-earthquake pull request #133
Opened 2024-12-24 05:10 UTC by amnak613

# Description

_add a short description_
- This PR add the feature of being able to share the report on different addresses through Email, Twitter, Facebook, and as a link.

_reference to relevant issue_
https://github.com/sfbrigade/datasci-earthquake/issues/126
## Type of changes
- [ ] Bugfix
- [ ] Chore
- [ X] New Feature

## Testing
- [ ] I added automated tests
- [X ] I think tests are unnecessary

## How to test
- Go to app search address and click share link and select method to share the link - IE Email, X, facebook, or by link
_testing description here: i.e. run app, go to x page, see that it does y_

2024-12-24 18:49 UTC, amnak613 commented
> @AdamFinkle ESLint seems to be failing due to my use of `` is there a way to format the code automatically or this this not allowed?

was able to fix after using code formatter

2025-01-09 03:08 UTC, nickvisut approved these changes
lgtm! good job.

2025-01-09 03:08 UTC, nickvisut commented on app/components/share.tsx
> +      console.log(window.location.href);
nit: no need for the logging

2025-01-09 03:38 UTC, amnak613 commented on app/components/share.tsx
> +      console.log(window.location.href);
Thanks! Will get rid of this

2025-01-09 03:57 UTC, nickvisut commented
Looks like Vercel deployments are blocking the pull requests. I'll prioritize fixing the build.

2025-01-09 19:53 UTC, mantuok requested changes
Other than a small spelling typo everything looks good to me.

2025-01-10 12:16 UTC, amnak613 commented on app/components/share.tsx
> +      const addreessParts = AddressData.address.split("");
Thanks! I went ahead and changed it

2025-01-12 02:18 UTC, mantuok approved these changes

2025-01-12 07:51 UTC, merged